name: Test run in the GitHub actions after each commit.

on:
  push:
    branches:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1' # Adjust the version as needed

      - name: Install npm
        run: npm install

      - name: Run npm build
        run: npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Download laravel Package

        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Sql lite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Create Database Tables
        run: php artisan migrate --env=testing --force

      - name: Check Unit Test
        run: php artisan test
